### ISSUE TITLE
Overhaul cloud config for clarity and maintainability

### ISSUE THREAD

**Issue by hillaryj** [cloud-gov/cg-product#1071]
In order to make cloud configurations easier to manage, we need to overhaul cloud config for clarity, maintainability, and organization.

- Config should define available instance types which get consumed later
  - vm types should reflect what's available in our region
  - Duplicate/overlapping definitions exist
- Helps reduce/deconflict manifests
- Brings staging and prod in line with each other

## Acceptance Criteria
* [ ] Define scope, tasking, and acceptance criteria
* [ ] Cloud configurations include no deprecated features

## Implementation sketch
- Are there industry standards or recommendations we can follow?
  - Pivotal Cloud Foundry has [guidelines](https://medium.com/@mxplusb/beyond-the-basics-adding-new-vm-types-to-pivotal-cloud-foundry-on-microsoft-azure-858ac9675b3f)

**Comment by karareinsel** [comment]
Important but not urgent.

**Comment by mxplusb** [comment]
Started a bit of work on this due to #1289 coming up, see https://github.com/18F/cg-deploy-bosh/pull/410 for the start of the work.
