### ISSUE TITLE
Import Shibboleth into Credhub

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/cg-product#1113]
In order to get Shibboleth credentials into Credhub, we need to import Shibboleth's variables into Credhub.

## Acceptance Criteria

- [x] Staging Shibboleth manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [x] Production Shibboleth manifest should be identical to existing manifest, but with variables pulled from Credhub.

**Comment by karareinsel** [comment]
Prioritize for sprint 19.11.13+

**Comment by mxplusb** [comment]
It turns out Spruce can actually generate a manifest without resolving all fields and then secrets can be resolved from Credhub, so this might be much easier than I originally thought.
