### ISSUE TITLE
kibana-upload-objects doesn't work in platform environments

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1120]
Kibana deprecated managing the .kibana index manually, and logsearch-for-cloudfoundry (correctly) responded by updating kibana objects using the kibana API. In platform environments, since we're not using UAA, these scripts don't work for us, and can't be easily modified to do so. We need to come up with a solution to allow us to run upload-kibana-objects or some equivalent against platform environments.

**Comment by hillaryj** [comment]
This will become urgent eventually but is currently stable.
