### ISSUE TITLE
Deploy Admin UI to dev environment

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/cg-product#1121]
In order to ensure all production assets are tested consistently and thoroughly, the Admin UI needs to be deployed to the development environment.

## Acceptance Criteria
- [ ] The Admin UI is available the development environment.

**Comment by karareinsel** [comment]
@eddietejeda and @jessykacastillo do you use the admin UI? Trying to determine the priority of this story.

**Comment by hillaryj** [comment]
This is a good idea as part of standardizing the environments, but the Admin UI doesn't change very often. @jessykacastillo occasionally uses the production admin ui.
