### ISSUE TITLE
switch upstream for 18F/oauth2_proxy to pusher/oauth2_proxy

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1141]
In order to stay secure and compliant, we want to switch the upstream of 18F/oauth2_proxy to pusher/oauth2_proxy.

Acceptance criteria:
- [ ] 18F/oauth2_proxy is a fork of pusher/oauth2_proxy (Since pusher was a hard-fork, I *think* we'll need to create a new fork in github.)
- [ ] 18F/oauth2_proxy retains http security settings:
  - HttpAllowedHosts
  - HttpHostsProxyHeaders
  - HttpSSLRedirect
  - HttpSSLTemporaryRedirect
  - HttpSSLHost
  - HttpSTSSeconds
  - HttpSTSIncludeSubdomains
  - HttpSTSPreload
  - HttpForceSTSHeader
  - HttpFrameDeny
  - HttpCustomFrameOptionsValue
  - HttpContentTypeNosniff
  - HttpBrowserXssFilter
  - HttpCustomBrowserXssValue
  - HttpContentSecurityPolicy
  - HttpPublicKey
  - HttpReferrerPolicy

**Comment by hillaryj** [comment]
Per previous discussion, this should be in the next few sprints.
