### ISSUE TITLE
Gather ALB/ELB metrics in prometheus

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1143]
In order to increase visibility into system access and performance, we should have prometheus scrape cloudwatch to get stats about our front-door ALB/ELBs

# Acceptance criteria
- [ ] prometheus is tracking response status codes for ALBs and ELBs that route customer traffic
- [ ] prometheus has alerts configured to detect misconfigured ALBs or ELBs

# Implementation sketch
- create boshrelease for https://github.com/prometheus/cloudwatch_exporter or add it to the existing prometheus boshrelease
- configure scraping on our customer-facing ALB and ELBs
- create a prometheus alert based on the ratio of 2xx to 4xx + 5xx responses

**Comment by hillaryj** [comment]
Priority is for the next few sprints.
