### ISSUE TITLE
limit or eliminate CFAppCrashed alerts

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1147]
prometheus is constantly complaining about CFAppCrashed and CFAppUnhealthy.
There are about 20 customer containers that have crashed or are unhealthy, and it's not an actionable alert.

It does seem reasonable to me that we should care if some threshold of customer instances goes offline, and that we should care about our own instances.

**Comment by hillaryj** [comment]
This is a nice-to-have as we reduce alert fatigue - if we remove the alert whole-sale without adding other alerting, then if our own apps crash (like cg-site or any of the brokers) then we won't get alerted.

This is lower priority than "next few sprints" and should be included in the alerting improvements.
