### ISSUE TITLE
secureproxy boshrelease test image doesn't exist

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1153]
There is a missing Docker image attempting to be pulled during the pipeline execution. 

In the last few weeks or so, the image we use for testing in the secureproxy boshrelease started giving a 401 error when we try to pull it. We need to figure out what's up with this and fix it so the pipeline can continue to run.

Pipeline has not been built since December 2017; may be less critical / important. Possibility that pipeline should be built more frequently or may be built within another pipeline. Additional discovery required.

**Comment by karareinsel** [comment]
Timebox to two hours as a research task.
