### ISSUE TITLE
Automatic migration from old to new cdn and custom domain plans

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-product#1154]
In order to streamline CDN and Custom Domain service instance migrations, we should write a tool to do them.

# Acceptance Criteria
- [ ] existing ALB/CloudFront config should not be updated
- [ ] existing Lets Encrypt accounts and certificates should be reused
- [ ] no downtime for users

Some features I think we should strive for, or have a story around why they cannot be provided:
- [ ] Retain the name of the service. Users may have automation around their systems that assumes the service name will not change
- [ ] Self service: making this self service would mean users can control service names (if they cannot be retained) and have a feeling of control over when this happens. Users don't like us making changes during their critical moments.
- [ ] Totally automatic: Ideally, we should only be running one script or one cf command per instance - no manual SQL changes, no copy-pasting, etc
- [ ] interact with CAPI only through cf commands - no poking around in CAPI's database by hand

**Comment by hillaryj** [comment]
This should be done relatively soon as part of the CDN broken work. Since these are for existing customers, they should be stable whether we do this soon or not, HOWEVER we should incorporate this work while the CDN broker changes are fresh in our brains. Prioritize in the next sprint or two.
