### ISSUE TITLE
Slack Webhooks (Feb. 24)

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/cg-product#1155]
Update all pipelines to use the correct slack webhook URL.

- [x] Download all credential files
- [x] Update the webhook url in all files
- [x] Upload all credential files
- [ ] One by one, update each pipeline using the `pipeline.yml` in the repo and the new credential file

**Comment by bengerman13** [comment]
Context for prioritization:
this is the primary source of alerts for:
- broken builds
- terraform changes requiring action
- **prometheus, our alerting system, being unhealthy**

**Comment by mxplusb** [comment]
@hillaryj any luck?

**Comment by hillaryj** [comment]
I requested a webhook last week via the request interface and it said I'd be notified by slackbot when my request was reviewed. I've posted a message following up with the slack admins on this.

**Comment by karareinsel** [comment]
@mxplusb will add the link to the google doc.

**Comment by mxplusb** [comment]
[Doc](https://docs.google.com/document/d/1UH0sn7S6Ci_sObHfWmYaja7evaLIioSgucKZB3FZSvU) and [tracking sheet](https://docs.google.com/spreadsheets/d/1XKfVlck0Hb6dEdq700NtfHwznFphs6sUumIVwOFGx7Q).

**Comment by tammersaleh** [comment]
Work needs to be restarted due to webhooks being tied to user accounts and Hillary's departure.

**Comment by hillaryj** [comment]
I checked into whether a webhook could be reassigned or assigned to a group of people and unfortunately they cannot. There may be a better approach that would let anyone rotate the cred other than having multiple webhooks to switch between (which doesn't close the "can post to our slack" hole after a spillage).

**Comment by hillaryj** [comment]
here’s the tracking spreadsheet for webhooks :lock: https://docs.google.com/spreadsheets/d/1XKfVlck0Hb6dEdq700NtfHwznFphs6sUumIVwOFGx7Q/edit#gid=1818613501

moving forward:
- we should probably request multiple so we can separate accounts/pipelines/environments
- see if we can use a robot account or Slack apps instead because linking the webhooks to a single user account makes changing/managing them more difficult

**Comment by tammersaleh** [comment]
@bengerman13 & @mxplusb I've updated the majority of the pipelines.  Please [see this spreadsheet](https://docs.google.com/spreadsheets/d/1XKfVlck0Hb6dEdq700NtfHwznFphs6sUumIVwOFGx7Q/edit#gid=1818613501).  

1. Many of the variables files don't seem to have a corresponding pipeline in concourse.  Please take a look and let me know in the spreadsheet if you know what pipeline they belong to.  If not, I'll assume we're no longer running them and **I'll remove the vars file from S3**.
1. For some of the pipelines, when I tried to apply the `pipeline.yml` from `master` given the new vars files, I got a lot of proposed changes.  This either means the pipelines are running from a branch, or from a local `pipeline.yml`, or that the `pipeline.yml` was lost.  **Can you let me know if you're actively working on any of those?**

**Comment by tammersaleh** [comment]
Moving to blocked until we get the sheet updated.

**Comment by tammersaleh** [comment]
Done
