### ISSUE TITLE
As a cg operator, I want to know the feasibility of providing elastic search and redis on kubernetes as an alternative to AWS.

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-product#1165]

**Comment by ChrisMcGowan** [comment]
Steve created a dev install of k8s using kops and installed kibosh on a separate vm.

@ChrisMcGowan is working on a staging k8s using kops for testing/validation
@soutenniza is working with the dev kibosh on helm charts for elasticsearch and redis

**Comment by ChrisMcGowan** [comment]
Latest update:

- Kibosh is deployed as a CF APP
- Nginx ingress controller deployed and working
- Elasticsearch 7.5.X is working with HTTP Host ingress thru AWS ELB
- Working on Redis HA with AWS NLB
- Working on backup tasks for k8s, broker, and services

**Comment by ChrisMcGowan** [comment]
Latest Update:

- Working on AMI upgrades to cluster
- AMI Upgrade Path
- VM Hardening
- ClamAV intergration
- 

-

**Comment by ChrisMcGowan** [comment]
Update:

* Base ClamAV daemon set is working and able to scan the host VM filesystem
* Work continues on FISMA hardening via daemon set (file side -  code exe side is still in discovery)
* Building out a custom AMI was shelved for now in favor of doing hardening/tools via daemon sets - we'll continue to use the latest canonical AMis as base (AWS govcloud account id 513442679011 )
* Research continues on daemon sets having the correct access to VM hosts for scan/ids tools
*

**Comment by karareinsel** [comment]
@ChrisMcGowan can you add an update?

**Comment by ChrisMcGowan** [comment]
Update:

- Pivoted away from daemon sets for install since not all sys calls work from a container to the host.  Daemon sets will be used for config changes for each env
- Using Packer to build AMIs based on the official KOPS Debian image and installing hardening and compliance tools into the AMI.
- Working on a process to move AMIs from the commercial space to govcloud

**Comment by karareinsel** [comment]
@ChrisMcGowan How close do you think we are to being able to do a beta with a few trusted customers?

**Comment by ChrisMcGowan** [comment]
Update:

- Still working on the AMI move process out of commercial and into AWS gov - once we have a working/repeatable process we'll have a better idea of turn-around
- Parallel efforts are moving forward on compliance tooling and hardening

**Comment by RonWilliams** [comment]
Thanks Chris -- When c.g staff met on February 6th regarding the K8s work, we expected the K8s work to take approximately 2 sprints. We're coming up on the 2 sprints and would like to have more visibility around timelines for service availability and any blockers / delays that push us beyond the discussed 2 sprints. 

Can you share the projected completion date? If later than the original 2 sprints, please outline the roadblocks encountered.

**Comment by ChrisMcGowan** [comment]
So at this point these where/are the blockers we currently face:

- We were using a base AMI inside the AWS gov space that was based on Ubuntu for our cluster VMs.  An issue we faced was it was a base Ubuntu VM with no pre-installed k8s code nor k8s kernel optimization.  The AMI did work as KOPs will compile that software at the time it creates a VM/adds a VM to the cluster but on average that takes between 12 - 18 min per VM.  Seeing as KOPs cluster operations are single threaded, AMI swap outs for patching would take us over 12 - 15 hours once the cluster was scaled out to production sizing.  We felt this was too long of a window for CG support to maintain effectively.

- The 2nd issue was while k8s does run on Ubuntu, it's not 100% certified - only Debian based OS images are certified but there are no current Debian AMIs in AWS Gov.  The only ones supplied are from AWS and on average are between 60-90 days old. Being so far out of date from a patching perspective and not wanting to take on more work support OS CVE patching we started to focus on importing known/current AMIs from AWS Commercial into AWS Gov which are patched on a regular basis inside of 30 days.

The other blocker we faced was trying to come up with a cohesive method of deploying CG Hardening and Compliance tools onto this cluster.  All of the current tooling is based on BOSH and not compatible and would require a new work stream to install the tools and do the hardening.  In discussions with other team members we tried an approach to do the install and configuration via k8s daemon sets but some of the tools, like snort, would not work regardless of how privileged me made the containers as not all the system calls where exposed from the host to the container.  This then pushed us down the path of baking in the tools into a AMI build process we are in now.

This afternoon we are working an issue on trying to export an AMI from AWS Commercial into AWS Gov.  AWS does not make this a simple process as gov is not considered another region.  We have found a few solutions but we also run into issues on what AWS gov supports vs AWS commercial.  The AWS gov side does not support all the latest features/settings that commercial does so through iteration testing we have run into a few errors that we are currently working on trying to resolve those errors.  Van will continue that work today.

If by mid-day tomorrow our path is still blocked, we can meet with the team to discuss other options as a path forward and what we are willing to manage and live with.

After we resolve the AMI issue, we should be able to offer the broker with some basic plans on a running cluster in beta in about a week.  Keep in mind that we will still be doing work behind the scenes (building out the automation, day X tasks like testing rolling updates, backups/restores, etc) so the expectation is there could be some disruption to the system. 
 We would suggest we have an open channel with the beta customers to make these communications know.

**Comment by ChrisMcGowan** [comment]
Update:

We where able to use the AWS Govcloud import tool to successfully pull a AMI from commercial into AWS Govcloud but the tool itself is not very robust and works about 2 out of 3 times we try to use it - we are still investigating ways to make that better and/or come up with a more solid process that does not use the tool.  The tool for reference: https://aws.amazon.com/blogs/publicsector/gov-cloud-import-tool-how-to-transfer-information-between-identity-boundaries/

Meanwhile we now have a recent/working image in AWS Govcloud and successfully applied a partial Packer build and made a custom AMI with snort and clamav for testing.  This image deployed successfully using KOPS.  We are now working on making daemon sets to apply environment specific configurations to the cluster.

**Comment by ChrisMcGowan** [comment]
Update: 

We have been able to reverse engineer the AWS process so we should be able to do the steps in a pipeline.

We have run some tests on the new image using a custom image with Snort and ClamAV:

- New node in now takes 5 min
- Rotate a node now takes 7-8 for a AMI swap

**Keep in mind this on a fresh cluster with no production load.

We did notice some inconsistent behavior with kube dns on the new AMI that needs checking/validation.

**Comment by ChrisMcGowan** [comment]
Update:
* Van is near having a scripted method to move AMIs from Com to Govcloud
* Still having trouble with kube-dns - errors still appear in logs but pods are stable
* Having issues with init scripts for compliance tools to keep services running
* Meeting later today with others on the team for next steps

**Comment by karareinsel** [comment]
Breaking this out into smaller stories.
