### ISSUE TITLE
As an FBI Crime Data Explorer developer, I want to know if DNSSEC can be used with custom domains on cloud.gov.

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-product#1172]
**Meeting is scheduled for 12/20.**

Below is a previous team email. This was sent before the domain broker became unavailable. It is unclear if this will work.

--- 

We met with Amazon team, and it looks like they will not be providing DNSSEC anytime soon. But in discussing options with my team, we may have a solution that we'd like to run by you.

Here's a summary of where we stand:

If you want to map crime-data-explorer.fr.cloud.gov to crime-data-explorer.fbi.gov, DNSSEC will fail because the root domain of cloud.gov does not support DNSSEC.

Although we use Amazon Route 53 for our domain, Cloud.gov services do not require us to be the sole DNS provider. That can be handled by any agency's DNS provider.

FBI's DNS provider currently supports DNSSEC.

By default, we use CNAMEs to create map to new domains.
Domain names can either other domains (CNAMEs) or to IP addresses (A Records). 

Here's what we can do:

Instead of mapping crime-data-explorer.fbi.gov to the crime-data-explorer.fr.cloud.gov CNAME, we can use your agency's DNSSEC-supported DNS provider and point to our application’s IP address (A record). 

Your agency will control every part of the FBI domain chain and will have no direct relationship to cloud.gov's domain name.

Here's how you do that:

Create a custom domain instance, as described here, stopping when you get to the step “How to set up DNS”

Get the service information:
$ cf service <service-name>

Last Operation

Status: create in progress

Message: Provisioning in progress; CNAME or ALIAS domain(s) my.example.gov to production-domains-0-792003535.us-gov-west-1.elb.amazonaws.com or create TXT record(s):

name: _acme-challenge.my.example.gov., value: <long string>, ttl: 120

Make node of the domain the instructions say to CNAME or ALIAS to (“production-domains-0-792003535.us-gov-west-1.elb.amazonaws.com” in the example above, yours will be different), and the TXT record

Create the TXT record as specified. This starts the process of provisioning your certificate. If this is a domain you’re currently using, wait until this process finishes before proceeding to the next step. You can check the status by running the cf service command again. If this is a new domain, you can carry on to the next step immediately.

Find the IP address of the domain the instructions gave you earlier:
$ nslookup production-domains-0-792003535.us-gov-west-1.elb.amazonaws.com
… 
Name: production-domains-0-792003535.us-gov-west-1.elb.amazonaws.com
Address: 1.2.3.4
…
$ nslookup -type=AAAA \
production-domains-0-792003535.us-gov-west-1.elb.amazonaws.com
…
<some domain>.elb.amazonaws.com has address 2001:db8:85a3::8a2e:370:7334
…
Create A and AAAA records for your domain (e.g. crime-data-explorer.fbi.gov) with the IP addresses you got from nslookup

Let me know if you need to talk this over with our team in more detail.

--- 

## Security considerations

TBD

## Implementation sketch

It is unclear if this is possible/feasible.

* [x] investigate the above team outline for feasibility
* [x] investigate the existing domain broker (non-cdn) funcationality
* [x] test DNSSEC with a sample domain

If it works:

* [x] Document what needs to be done while the domain broker is unavailable
* [x] Document what the new domain broker needs to implement to ensure this functionality is available

**Comment by spgreenberg** [comment]
I have a working solution for the FBI meeting. I will update the docs and commit a PR after this.

**Comment by spgreenberg** [comment]
https://github.com/18F/cf-domain-broker/pull/4

**Comment by tammersaleh** [comment]
We've requested that AWS apply a range of static IP addresses to our ALBs.  The support ticket is 6725567341.

**Comment by tammersaleh** [comment]
Link to ticket: https://us-gov-west-1.console.amazonaws-us-gov.com/support/cases#/6725567341/en

**Comment by tammersaleh** [comment]
Here's the response from AWS support.  I'd like to respond that this won't work for us and that we're investigating alternative solutions, closing the case.  Any objections?

> I reached out to with my internal team. They confirmed that currently ALB doesn’t support static IPs. I understand they may be able to **allocate a pool of IPs which ALB will be using when needed to support its scaling.**
>
> Please let me know if it suits your use-case. One contention I see here is, though ALB will be using the IPs from a pool of IPs, **IP assigned to ALB can still dynamically change (from within the pool of allocated IPs)** due to many factors including but not limited to scaling-up/down to support magnitude of incoming traffic. As you will be using static IP (at your DNS record) instead of DNS name any request made to the IP which ALB is not currently using will fail. To overcome this my internal team suggested to use NLB infront of ALB, which I understand you have previously ruled out due to cost factor.
> 
> May I suggest to consider using Global Accelerator to front your ALB if it suits your use case?  AWS Global Accelerator is a service that improves the availability and performance of your applications with local or global users. It provides static IP addresses that act as a fixed entry point to your application endpoints in a single or multiple AWS Regions, such as your Application Load Balancers, Network Load Balancers or Amazon EC2 instances. Pricing information for Global Accelerator can be found here [2].

**Comment by karareinsel** [comment]
@RonWilliams will coordinate with @jessykacastillo to contact FBI.

**Comment by karareinsel** [comment]
Email sent to FBI 3/3/2020 advising them that the best solution is using their existing Cloudflare integration.
