### ISSUE TITLE
Pay forward on 2020 assessment experience (March 13)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-product#1181]
In order to make our next assessment easier, faster and less stressful,  cloud.gov team members should put work in place as soon as possible some documentation and next steps. 

## Acceptance Criteria

_n/a_ 

--- 

## Security considerations

In the event that we're discussing potential weaknesses, or operational characteristics, start with Google Docs that are internal only.

## Implementation sketch

During assessment:

- [x] Start a "Notes for 2020-2021 assessment" and start contributing
- [x] Schedule retrospective

Post-assessment: 

- [ ] Hold retrospective
- [ ] Post assessments:
- [ ] Gather email threads into GDocs so they're searchable by potential future team members.

**Comment by pburkholder** [comment]
https://docs.google.com/document/d/1mJjIp3kRY9V-y_i8sZi7YGiYYxaD_9JkOfz3E1IDgnc/edit?folder=17yROcLI3_fXCHwKIgxitfAidcxGrzfrA for the Notes document, readable cloud.gov team only

**Comment by karareinsel** [comment]
The retro is scheduled for Jan. 22.

**Comment by karareinsel** [comment]
The retro was rescheduled for Jan. 30.

**Comment by karareinsel** [comment]
@RonWilliams should this be closed since the retro was canceled?

**Comment by pburkholder** [comment]
Seems like this isn't happening.  :(
