### ISSUE TITLE
Dashboard banner on cloud.gov (Mar. 6)

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-product#1184]
As a cloud.gov team member, I want to direct cloud.gov customers to use the new beta dashboard and discontinue using the old dashboard which has broken functionality.

AC

- [x] ~Implement banner message on cloud.gov to direct customers to the beta dashboard~
- [x] Add instructions for the beta dashboard to cloud.gov's how to manage users page 
- [x] Push blog post live (#1200) 
- [x] Update StatusPage with maintenance announcement that the old dashboard is being deprecated as of 3/6/2020
- [x] On 3/6, run `cf map-route` to the map the `stratos` app in `cloud-gov` so that both https://dashboard.fr.cloud.gov/ and https://dashboard-beta.fr.cloud.gov/ point to the same Stratos dashboard with a zero down time cutover (in-progress sessions will experience issues, thus the maintenance window)
- [x] Docs updates
  - [x] Update https://cloud.gov/docs/orgs-spaces/dashboard/ to remove references to the "new dashboard"
  - [x] Update the "dashboard" text link on https://cloud.gov/docs/orgs-spaces/roles/
  - [x] Update "After a user has a cloud.gov account, an Org Manager can assign roles using the dashboard" text link on https://cloud.gov/docs/orgs-spaces/roles/
- [ ] After a couple days, clean up cg-dashboard
  - [ ] Remove cf app
  - [ ] Stop/remove deployment pipeline
  - [ ] Archive the repository

**Comment by hillaryj** [comment]
Currently, the instructions I used in Slack and only needs minor updates to get added to cg-site:

1. For anyone without a cloud.gov account, use https://account.fr.cloud.gov/invite to invite them. You’ll likely need to log in first and may need to click on an “Invite Users” button and does not require someone to have a .gov or .mil address.
2. Log into the Beta Dashboard (https://dashboard-beta.fr.cloud.gov)
3. In the left menu, the “Cloud Foundry” entry to manage orgs & spaces
4. In the top blue bar, click on the “Organizations” tab, then click on the organization you would like to manage
5. Click on the “Users” box at the bottom or in the top blue bar
6. Set the left dropdown to “Users without roles” or “All users”, then in the right “Search by username”, click and start typing their email address (or some subset, like the domain name of a contractor)
7. To the right of the user you want to manage, click the three-dot menu and select “Manage roles”
8. You’ll then be able to use checkboxes to set the roles for the org and spaces within that org for that user
9. Click "Apply" and confirm the resulting role changes are good, then apply them.

**Comment by mogul** [comment]
Note that Stratos now supports inline invitations, much like our old dashboard used to before it got b0rken. 
https://github.com/cloudfoundry/stratos/blob/master/docs/invite-user-guide.md

You might want to take a crack at configuring that functionality since it will simplify the instructions quite a bit.

**Comment by hillaryj** [comment]
Instructions are now graphically assisted and up as a PR to cg-site https://github.com/18F/cg-site/pull/1521

**Comment by hillaryj** [comment]
PR for the `cg-dashboard` changes is now live! Includes screenshots of the UI changes:

https://github.com/18F/cg-dashboard/pull/1325

**Comment by karareinsel** [comment]
Is the PR pending @eddietejeda and @RonWilliams review?

**Comment by eddietejeda** [comment]
Build failing?

**Comment by karareinsel** [comment]
@hillaryj and @mxplusb pairing 1/28 to fix CircleCI certs - once that's done then this should be ready to push. @pburkholder also available to pair.

**Comment by hillaryj** [comment]
@pburkholder and I got the CircleCI configuration working, but then it failed when trying to deploy to staging. I've moved to working on using `cf push` to update the dashboard with this banner.

@mxplusb and I are going to pair this afternoon to try to close it out.

**Comment by mxplusb** [comment]
Paired with @hillaryj, fixed CircleCI but caused other problems neither of us understand, my personal recommendation is to just close this out with a blog post because we don't understand why it's not working.

**Comment by karareinsel** [comment]
Agree that it makes sense to just wrap this up. So after talking to @hillaryj these are the next steps:

- [ ] Update Status Page with announcement that the old dashboard is being deprecated as of 3/6/2020
- [ ] Update the DNS record to point straight to Stratos so that both https://dashboard.fr.cloud.gov/ and https://dashboard-beta.fr.cloud.gov/ point to the same Stratos dashboard
- [ ] Update https://cloud.gov/docs/orgs-spaces/dashboard/ to remove references to the "new dashboard"
- [ ] Update the "dashboard" text link on https://cloud.gov/docs/orgs-spaces/roles/
- [ ] Update "After a user has a cloud.gov account, an Org Manager can assign roles using the dashboard" text link on https://cloud.gov/docs/orgs-spaces/roles/
- [ ] Push blog post live (#1200) 

-

**Comment by hillaryj** [comment]
The “Status Page” update should probably be an announced maintenance window on the `Customer Components -> Dashboard`. I'll draft up a message to announce this occurring.

**Comment by hillaryj** [comment]
StatusPage maintenance window for 3/6 needs a start/end time and the link to the blog post when it goes live. Here's a draft of some text that can be used for the description when :lock: [creating a new scheduled maintenance](https://manage.statuspage.io/pages/swcbylb1c30f/incidents/new-scheduled-maintenance).

> At this time, we'll be deprecating the old cg-dashboard in favor of our now-beta Stratos-based dashboard (https://github.com/cloudfoundry/stratos). There may be some brief interruptions to https://dashboard.fr.cloud.gov/ but service availability at https://dashboard-beta.fr.cloud.gov/ should be uninterrupted.
> 
> Our documentation for managing orgs, roles, and spaces (https://cloud.gov/docs/orgs-spaces/roles/) has been updated to reflect the Stratos approach. For more information, please see our blog post about the dashboard changeover at ().

**Comment by hillaryj** [comment]
@spgreenberg notes than since both dashboards are apps, we can use `cf map-route` for a zero-downtime cutover, to be followed by a later removal of the cg-dashboard app.

**Comment by spgreenberg** [comment]
This update is complete. Note I also had to change the `redirect_uri` in UAA to reflect the updated route.
