### ISSUE TITLE
Blog post announcing new dashboard

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-product#1200]
As a cloud.gov customer, I want to learn about the new cloud.gov dashboard, its features and functionality, and how to use it so that I can discontinue using the old dashboard.

As a cloud.gov operator, I want to educate customers about the new dashboard so that I can deprecate the old dashboard.

**Comment by GaryHall191** [comment]
@hillaryj Here's a shot at a rough draft.  I'm open to suggestions or totally ok with anyone's edits.

https://docs.google.com/document/d/1h54ggWD7WQAVGVXin_cOBaGE59VMxDKrXMcRrvv2XnU/edit?usp=sharing

**Comment by karareinsel** [comment]
Added comments to the doc.

**Comment by karareinsel** [comment]
The blog post is with the writing lab for final edits and review.

**Comment by karareinsel** [comment]
Update blog post once steps are complete in #1184

**Comment by hillaryj** [comment]
This is live! Closing.

https://cloud.gov/2020/02/27/new-dashboard/
