### ISSUE TITLE
Read-only service keys

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-product#1201]
# What we're after
Support for service keys, in particular read-only service keys, for the S3 and RDS service brokers.

## Hypothesized benefit(s)/why:
* Customers can provide read-only access to service instances

---

### Security considerations
This would allow our customers to have finer grain access control to service instances.

**Comment by tammersaleh** [comment]
Is this for the customers (who already have r/w access), or for the customer's users (who they may want to provide ro access)?

**Comment by karareinsel** [comment]
Customer's users.
