### ISSUE TITLE
Anti-virus as a service

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-product#1202]
# What we're after
An anti-virus as a service available to customers and applications.

## Hypothesized benefit(s)/why:
* Customers could run anti-virus against applications before they're pushed to cloud.gov
* Customer applications can leverage anti-virus scanning for uploads

---
###Security considerations
* Improved security for running applications that leverage the service

**Comment by pburkholder** [comment]
https://cloud.gov/docs/apps/experimental/behavior-monitoring/ is related, and possibly more important. But I hope we can get some background on https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1535472498000100 so customers can DIY it for now.
