### ISSUE TITLE
Compliance for dev documentation solutions

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/cg-product#1284]
As a cloud.gov operator, I want to ensure the following developer documentation solutions we are considering as a team meets compliance requirements.
- Private GH repos 
- AWS CodeCommit
- Google Code Source

AC

- [ ] Check with TTS Tech Portfolio
- [ ] If ok'd by TTS Tech Portfolio team, confirm with FedRAMP team

**Comment by pburkholder** [comment]
I think there's some merit in not bringing another service into our scope with CodeCommit. I'd suggest we try doing something in private GH repos with git-crypt. 

I also should pass this work off to someone else on the team. My WIP is pretty high and at this point it's a technical assessment/trial more so than compliance.

References:

https://docs.google.com/document/d/1ghlRtjkLiqmrmtQ4mgyInCkxZdCB5hb7r9_V4Vye4FA/edit?usp=sharing

https://gsa-tts.slack.com/archives/CG8SNAEQM/p1582058822115900 and

**Comment by karareinsel** [comment]
cloud.gov's own GH has been created - cg-product, cg-site, and cg-private will be moved over first.

**Comment by pburkholder** [comment]
@tammersaleh and myself pairing on this today.
