### ISSUE TITLE
As a user, I want the old dashboard back until Stratos supports full user management

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cg-product#1318]
Stratos currently has a bug where users cannot be assigned to an org/space unless the user already has a role in that org/space. More details: https://docs.google.com/document/d/1v789S9sjHnAhSk5jDVJJ4hb_x3jBs1IG4kCtlAIlKGc/edit

Therefore, we need to bring back the old dashboard.

## Acceptance Criteria

The cg-dashboard is available along with stratos and updated documentation.

--- 

## Security considerations

none. was previously used in the same form.

## Implementation sketch

Actions
* [x] Update UAA client for cg-dashboard with the correct redirect_uri in the pipeline
* [x] Unarchive the cg-dashboard repo
* [x] Update the hostname in the circle CI deploy of cg-dashboard to dashboard-deprecated
* [x] Restore circle ci access to the cg-dashboard repo
* [x] Manually update redirect_uri field for `dashboard` client in UAA staging and prod as builds are paused/failing
* [x] Update docs to reflect the use of cg-dashboard for user management
* [x] Update cg-dashboard links in docs to dashboard-deprecated

Validation
* [x] Deploy via circle ci and validate the hostname is dashboard-deprecated
* [x] Validate login works
* [x] Validate a user not in an org can be assigned to a role in a space
* [x] Validate user management docs align with cg-dashboard functionality

**Comment by spgreenberg** [comment]
@bengerman13 @tammersaleh Can you please review the impl steps and validation? Anything missing based on the dashboard-beta changes?

**Comment by bengerman13** [comment]
implied but not stated in your sketch is restoring circleCI's access to the repo

**Comment by spgreenberg** [comment]
@bengerman13 Can you renable circle ci access to cg-dashboard? I don't think I have the right access. Circle ci wants to see all of my orgs tied to my github account which isn't what we want.
