### ISSUE TITLE
Stratos invitations work

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-product#910]
In order to enable decommission of cg-dashboard, we want Stratos to support self-service invitation of new users to orgs and spaces.

---

Directions from the Stratos team:
> the setup docs are in docs/invite-user-guide.md, backend code in /src/jetstream/plugins/userinvite and email templates src/jetstream/templates

**Comment by hillaryj** [comment]
Reopening because this still needs to be done.

Docs on how are here: https://github.com/cloudfoundry/stratos/blob/master/docs/invite-user-guide.md

**Comment by karareinsel** [comment]
Current invite process works but this will create a better user experience to issue invites from Stratos directly. Users will be able to invite non-gov email addresses. Good to do but not urgent.
