### ISSUE TITLE
Eliminate dashboard overhead

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-product#911]
**What we're after:** cg-dashboard is fully deprecated and removed from our deployment and compliance docs

**Hypothesized benefit(s):**
- For customers
  - Better new user experience
  - Deploy-from-repo
  - Web SSH
  - Service instance parameter forms
- For us
  - Reduces support burden for invitations
  - Reduced security risk and compliance burden
  - Reduced maintenance and support burden
  - More practice decommissioning a customer-facing UI
  - Reduces friction for other features
    - Foundation for gov-specific features (eg auditing dashboard)
    - Metrics visualization
    - Auto-scaling

**Comment by hillaryj** [comment]
Issues that are part of retiring the old dashboard:

- #906 Stratos matches cloud.gov branding
- #903 cloud.gov’s dashboard has sufficient government required accessibility (508 compliance)
- #910 Stratos invitations work
- #911 Eliminate dashboard overhead
- #940 Push cg-dashboard into the :volcano:

**Comment by mogul** [comment]
There is a [page in the docs that includes instructions and screenshots for using cg-dashboard](https://github.com/18F/cg-site/blob/master/content/docs/apps/managing-teammates.md)... Search for "alternatives" there. That will need updating/eliminating too. https://github.com/18f/cg-product/issues/909 tried to cover that (though never with proper grooming)... The idea was that once the switch happens, the docs get updated with fresh instructions/screenshots.

**Comment by karareinsel** [comment]
This is done.
