### ISSUE TITLE
Ensure new RDS instances are getting the latest version available

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-product#920]
In order to ensure customers won't be dinged for running a vulnerable database, we want customers to be using supported, up-to-date versions of RDS instances.

## Acceptance Criteria
- [ ] WHEN I look at the list of RDS plans on cloud.gov, THEN I see that the versions listed are recent and non-vulnerable versions.
- [ ] WHEN I create-service on any RDS plan, THEN I see that the version created matches the version listed in the plan.

## Implementation sketch
- Update the docs page
- Update the plans in the broker

**Comment by karareinsel** [comment]
This is a compliance requirements so let's find time to address in the next 2-3 sprints.

**Comment by karareinsel** [comment]
Do this and then address it as part of ongoing maintenance moving forward.

**Comment by tammersaleh** [comment]
Provisioning a dedicated PostgreSQL instance results in the latest version as decided by AWS.  This is now documented.  Shared PostgreSQL instances will soon be running `9.5.15`, which is under support, but not the latest version.  

For MySQL:  Dedicated instances are pinned to `5.7.21`.  We could make a story to treat them the same as PostgreSQL, provisioning whatever the latest version happens to be.  The shared instance is at `5.6.41`.

Upgrading the shared instances isn't easy:  We must create entirely new shared plans for the new versions, set a deprecation policy, give users time to migrate, and eventually kill off the old plan.

If we want to do this, we should make separate tickets for:
1. Upgrading shared instances using our deprecation policy and
2. Un-pinning the MySQL version.

**Comment by karareinsel** [comment]
@tammersaleh I'm closing this issue in favor of creating separate tickets for the above when the time is ready.
