### ISSUE TITLE
Merge Cloudfront and CDN brokers

### ISSUE THREAD

**Issue by mogul** [cloud-gov/cg-product#999]
In order to increase the reliability of the services and enable the cloud.gov team to spend less effort on support, maintenance, and feature additions, the team wants a single domain-broker service that can handle certificate provisioning and optionally supply CDN services.

(Out of scope: Changing anything about the Let's Encrypt interaction.)

## Acceptance Criteria
- [ ] Users have a clear option for only using FedRAMP'd services (eg Cloudfront-free plan)
- [ ] We're maintaining just a single GitHub repository and Concourse pipeline
- [ ] User-facing service documentation is updated to reflect a single service
- [ ] Users of the existing service have a documented migration path and are notified of the deadline

---

## Implementation sketch
- Start fresh on the new broker codebase
- Decide how much of the existing code/logic should be migrated in
- Minimize the user-facing hassle for users to migrate from the previous to the new service without breaking anything (eg a push-button app).

**Comment by bengerman13** [comment]
This is a better descriptor of what @mxplusb  is working on right now

**Comment by mxplusb** [comment]
Yeah, more or less.

**Comment by mxplusb** [comment]
This work is still in the background as potential action item, but for now it can be stale.
